version: '3.8'

services:
  db:
    image: postgres:13
    container_name: rust_db
    restart: always
    environment:
      POSTGRES_USER: rust_user
      POSTGRES_PASSWORD: rust_password
      POSTGRES_DB: rust_database
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
volumes:
  app_data:
  postgres_data:
